### PR TITLE
Add OpenMetadata

### PR DESCRIPTION
**Pull request by ayush-shah**
#### ℹ️ Repository information

**The repository has**:

- [x] At least three issues with the `good first issue` label.
- [x] At least 10 contributors.
- [x] Detailed setup instructions for the project.
- [x] CONTRIBUTING.md
- [x] Actively maintained.

### CODE REVIEW

**Comment by lucavallin** [comment]
Thank you for your contribution! In the meantime, I moved `repositories.toml` to the root directory so it's very visible to new contributors. If you could update that, I will merge this PR asap.

**Comment by ayush-shah** [comment]
Cool, I will make that change, thanks

**Comment by ayush-shah** [comment]
Looks like it's already merged, Thanks @lucavallin

**Comment by ayush-shah** [comment]
Reopening a new one..

**Pull request closed without merging**
